// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_book.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createBookProcedure = `-- name: CreateBookProcedure :exec
CALL insert_book($1::UUID, $2::JSONB)
`

type CreateBookProcedureParams struct {
	BookID   uuid.UUID
	BookData json.RawMessage
}

func (q *Queries) CreateBookProcedure(ctx context.Context, arg CreateBookProcedureParams) error {
	_, err := q.db.ExecContext(ctx, createBookProcedure, arg.BookID, arg.BookData)
	return err
}
