// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: versions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createVersion = `-- name: CreateVersion :one
INSERT INTO 
    versions (id, created_at, updated_at, name, abbr)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, abbr
`

type CreateVersionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Abbr      sql.NullString
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, createVersion,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Abbr,
	)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Abbr,
	)
	return i, err
}
